#based on: https://blog.nashtechglobal.com/a-workflow-for-nuget-packages-using-github-actions/
name: Build and Publish to NuGet

on:
  workflow_dispatch:  # This enables the manual trigger
  push:
    tags:
        - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.x'

    - name: Restore NuGet packages
      run: dotnet restore src/Microsoft.SolverFoundation/Microsoft.SolverFoundation.csproj

    - name: Build the project
      run: dotnet build src/Microsoft.SolverFoundation/Microsoft.SolverFoundation.csproj --configuration Release

    - name: Pack the project
      run: dotnet pack src/Microsoft.SolverFoundation/Microsoft.SolverFoundation.csproj --configuration Release --no-build

    - name: Publish to NuGet
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push src/Microsoft.SolverFoundation/bin/Release/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
